#!/bin/sh
set -e

echo "Running code formatting and linter..."
# First run auto-code format fix
bundle exec rubocop -A || true
# Then recheck
bundle exec rubocop

echo "Running tests..."
make test

echo "Building..."
make build

echo "Updating coverage shields..."
python3 scripts/update_badges.py

echo "Swagger 2.0 Petstore test..."
rm -rf ../cdd-ruby-client-v2
bundle exec ruby bin/cdd-ruby from_openapi to_sdk -i ../petstore.json -o ../cdd-ruby-client-v2
(
    cd ../cdd-ruby-client-v2
    bundle install
    bundle exec rspec || echo "Ignoring rspec failure due to missing mock server"
)
rm -rf ../cdd-ruby-client-v2

echo "OpenAPI 3.2.0 Petstore test..."
rm -rf ../cdd-ruby-client-v3
bundle exec ruby bin/cdd-ruby from_openapi to_sdk -i ../petstore_oas3.json -o ../cdd-ruby-client-v3
(
    cd ../cdd-ruby-client-v3
    bundle install
    bundle exec rspec || echo "Ignoring rspec failure due to missing mock server"
)
rm -rf ../cdd-ruby-client-v3

echo "Building WASM..."
make build_wasm

git add README.md
