#!/bin/sh
set -e

echo "Running code formatting and linter..."
# First run auto-code format fix
bundle exec rubocop -A || true
# Then recheck
bundle exec rubocop

echo "Running tests..."
make test

echo "Building..."
make build

echo "Updating coverage shields..."
python3 scripts/update_badges.py

git add README.md
