repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: \.(bat|cmd|ps1)$

  - repo: local
    hooks:
      - id: auto-format
        name: Auto Format
        entry: bundle exec rubocop -A
        language: system
        types: [ruby]
        pass_filenames: false

      - id: lint
        name: Lint
        entry: bundle exec rubocop
        language: system
        types: [ruby]
        pass_filenames: false

      - id: build
        name: Build
        entry: python3 scripts/build.py
        language: system
        pass_filenames: false

      - id: test
        name: Test
        entry: bundle exec rspec
        language: system
        pass_filenames: false

      - id: update-badges
        name: Update Badges
        entry: python3 scripts/update_coverage.py
        language: system
        pass_filenames: false

      - id: test-petstore-swagger-2
        name: E2E Test SDK (Swagger 2.0) against Docker
        entry: scripts/run_slow.sh python3 scripts/test_petstore_swagger_2.py
        language: system
        pass_filenames: false

      - id: test-petstore-openapi-3
        name: E2E Test SDK (OpenAPI 3.0) against Docker
        entry: scripts/run_slow.sh python3 scripts/test_petstore_openapi_3.py
        language: system
        pass_filenames: false

      - id: test-generated-server-swagger-2
        name: E2E Test Generated Server (Swagger 2.0) natively
        entry: scripts/run_slow.sh python3 scripts/test_generated_server_swagger_2.py
        language: system
        pass_filenames: false

      - id: test-generated-server-openapi-3
        name: E2E Test Generated Server (OpenAPI 3.0) natively
        entry: scripts/run_slow.sh python3 scripts/test_generated_server_openapi_3.py
        language: system
        pass_filenames: false

      - id: build-wasm
        name: Build WASM
        entry: python3 scripts/build_wasm.py
        language: system
        pass_filenames: false
