inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'build/**/*'
    - 'coverage/**/*'
    - 'dist/**/*'
    - 'rubies/**/*'
    - 'docs/**/*'
    - '.yardoc/**/*'
    - 'bin/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'src/cli.rb'

Metrics/ClassLength:
  Exclude:
    - 'src/docstrings/parse.rb'

Metrics/MethodLength:
  Exclude:
    - 'src/docstrings/parse.rb'

Metrics/BlockLength:
  Exclude:
    - 'src/docstrings/parse.rb'

Style/EmptyElse:
  Exclude:
    - 'src/docstrings/parse.rb'

Style/Documentation:
  Exclude:
    - 'src/cli.rb'
    - 'spec/**/*'
