inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'build/**/*'
    - 'coverage/**/*'
    - 'dist/**/*'
    - 'rubies/**/*'
    - 'docs/**/*'
    - '.yardoc/**/*'
    - 'bin/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'src/cli.rb'

Style/Documentation:
  Exclude:
    - 'src/cli.rb'
    - 'spec/**/*'
